DROP SCHEMA IF EXISTS FREERIDER_DB;

CREATE SCHEMA IF NOT EXISTS FREERIDER_DB;
USE FREERIDER_DB;


DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER (
  ID INT NOT NULL,
  NAME VARCHAR(60) DEFAULT NULL,
  CONTACT VARCHAR(60) DEFAULT NULL,
  STATUS ENUM('Active', 'InRegistration', 'Terminated') DEFAULT NULL,
  PRIMARY KEY (ID)
);


DROP TABLE IF EXISTS VEHICLE;
CREATE TABLE VEHICLE (
  ID INT NOT NULL,
  /* --complete schema based on ERD-diagram */
  /* -- */
  MAKE VARCHAR(60) DEFAULT NULL,
  MODEL VARCHAR(60) DEFAULT NULL,
  SEATS INT DEFAULT 4,
  CATEGORY ENUM('Sedan', 'SUV', 'Convertible', 'Van', 'Bike') DEFAULT NULL,
  POWER ENUM('Gasoline', 'Diesel', 'Electric', 'Hybrid', 'Hydrogen') DEFAULT NULL, 
  STATUS ENUM('Active', 'Serviced', 'Terminated') DEFAULT NULL,
  PRIMARY KEY (ID)
);


DROP TABLE IF EXISTS RESERVATION;
CREATE TABLE RESERVATION (
  ID INT NOT NULL,
  CUSTOMER_ID INT NOT NULL,
  VEHICLE_ID INT NOT NULL,
  BEGIN DATETIME,
  END DATETIME,
  PICKUP VARCHAR(48) DEFAULT NULL,
  DROPOFF VARCHAR(48) DEFAULT NULL,
  STATUS ENUM('Inquired', 'InquiryConfirmed', 'Booked', 'Cancelled') DEFAULT NULL, 
  /* --complete schema based on ERD-diagram */
  /* -- */
  PRIMARY KEY (ID),
  /* --complete schema based on ERD-diagram */
  /* -- */
  KEY IDX_CUSTOMER_ID (CUSTOMER_ID),
  CONSTRAINT CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID),
  CONSTRAINT VEHICLE_ID FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE (ID)
  /* -- */
);
